packages:
  - "."
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "core-js-pure"
  - "prisma"
allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  "core-js-pure": true
  "prisma": true
